robot_3:
  controller_manager:
    ros__parameters:
      update_rate: 1000  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      forward_velocity_controller:
        type: forward_command_controller/ForwardCommandController

  forward_velocity_controller:
    ros__parameters:
      joints:
        - robot_3_first_wheel_joint
        - robot_3_second_wheel_joint
        - robot_3_third_wheel_joint
        - robot_3_forth_wheel_joint
      interface_name: velocity
      command_interfaces:
        - velocity
      state_interfaces:
        - velocity
        - position
