# controller configuration for gazebo ros control

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# individual velocity controllers
first_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: robot_1_first_wheel_joint
  pid: {p: 0.5, i: 0.1, d: 0.0}

second_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: robot_1_second_wheel_joint
  pid: {p: 0.5, i: 0.1, d: 0.0}

third_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: robot_1_third_wheel_joint
  pid: {p: 0.5, i: 0.1, d: 0.0}

forth_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: robot_1_forth_wheel_joint
  pid: {p: 0.5, i: 0.1, d: 0.0}